[project]
name = "llm-service"
version = "0.9.0"
description = "Serwer LLM, do analizy zgłoszeń"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.2",
    "huggingface-hub>=0.36.0",
    "torch>=2.9.1",
    "transformers>=4.57.1",
    "uvicorn>=0.38.0",
]
