services:
  database:
    build:
      context: ./database
    container_name: zglosto-postgres
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "${POSTGRES_PORT:-54325}:${POSTGRES_PORT}"
    command: ["postgres", "-c", "port=${POSTGRES_PORT}"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - pgbackrest-data:/var/lib/pgbackrest
      - ./database/init-scripts:/docker-entrypoint-initdb.d
      - ./database/pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf
    networks:
      - internal-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER:-zglosto_user} -d ${POSTGRES_DB:-zglosto_db}"]
      interval: 4s
      timeout: 4s
      retries: 5

  authorization:
    build:
      context: ./authorization
    ports:
      - "9955:9955"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal-net
  
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal-net

  llm_service:
    build:
      context: ./llm_service
    ports:
      - "8123:8123"
    env_file:
      - .env
    volumes:
      - huggingface-cache:/root/.cache/huggingface
    networks:
      - internal-net
    deploy:
      resources:
        limits:
          memory: 8GB

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - external-net

  nginx:
    build:
      context: ./nginx
    ports:
      - "1235:1235"
    depends_on:
      - backend
      - frontend
    networks:
      - internal-net
      - external-net

volumes:
  postgres-data:
    driver: local
  pgbackrest-data:
    driver: local
  huggingface-cache:
    driver: local

networks:
  internal-net:
    driver: bridge
  external-net:
    driver: bridge
