services:
  database:
    build:
      context: ./database
    container_name: zglosto-postgres
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - "${POSTGRES_PORT:-54325}:${POSTGRES_PORT}"
    command: ["postgres", "-c", "port=${POSTGRES_PORT}"]
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - zglosto-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER:-zglosto_user} -d ${POSTGRES_DB:-zglosto_db}"]
      interval: 4s
      timeout: 4s
      retries: 5

  authorization:
    build:
      context: ./authorization
    ports:
      - "9955:9955"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - zglosto-net
  
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - zglosto-net

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - zglosto-net

  nginx:
    build:
      context: ./nginx
    ports:
      - "1235:1235"
    depends_on:
      - backend
      - frontend
    networks:
      - zglosto-net

volumes:
  postgres-data:
    driver: local

networks:
  zglosto-net:
    driver: bridge
