apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zglosto-ingress
  namespace: zglosto
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/upstream-fail-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/load-balance: "least_conn"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost  # Zmień na swoją domenę
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 1235
      - path: /pgadmin
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 9753
