apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbackrest-config
  namespace: zglosto
data:
  pgbackrest.conf: |
    [global]
    repo1-path=/var/lib/pgbackrest
    process-max=2
    log-level-console=info

    [zglosto_db]
    pg1-path=/var/lib/postgresql/data
    pg1-port=
    pg1-user=
