apiVersion: v1
kind: Secret
metadata:
  name: zglosto-secret
  namespace: zglosto
type: Opaque
stringData:
  # Has≈Ça zakodowane w base64
  POSTGRES_PASSWORD:
  PGADMIN_DEFAULT_PASSWORD:
  DATABASE_URL:

  # Authentication secrets
  BETTER_AUTH_SECRET:

  # LLM service secrets
  HF_TOKEN: