apiVersion: v1
kind: Service
metadata:
  name: authorization
  namespace: zglosto
  labels:
    app: authorization
spec:
  selector:
    app: authorization
  ports:
  - name: http
    port: 9955
    targetPort: 9955
    protocol: TCP
  type: ClusterIP




