apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: zglosto
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
  - name: postgresql
    port: 54325
    targetPort: 54325
    protocol: TCP
  type: ClusterIP




